[package]
name = "cs-mail-security"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cs-mail-primitives = { path = "../cs-mail-primitives" }
cs-mail-protocol = { path = "../cs-mail-protocol" }
cs-mail-wire = { path = "../cs-mail-wire" }
ed25519-dalek.workspace = true
sha2.workspace = true

[lints]
workspace = true
