[package]
name = "cs-mail-worker"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cs-mail-content = { path = "../cs-mail-content" }
cs-mail-primitives = { path = "../cs-mail-primitives" }
cs-mail-protocol = { path = "../cs-mail-protocol" }
cs-mail-storage-postgres = { path = "../cs-mail-storage-postgres" }

[dev-dependencies]
cs-mail-security = { path = "../cs-mail-security" }

[lints]
workspace = true
