[package]
name = "cs-mail-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cs-mail-correspondence = { path = "../cs-mail-correspondence" }
cs-mail-application = { path = "../cs-mail-application" }
serde_json.workspace = true
getrandom = "0.4.3"
cs-mail-finance = { path = "../cs-mail-finance" }
cs-mail-billing = { path = "../cs-mail-billing" }
cs-mail-content = { path = "../cs-mail-content" }
cs-mail-primitives = { path = "../cs-mail-primitives" }
cs-mail-protocol = { path = "../cs-mail-protocol" }
cs-mail-security = { path = "../cs-mail-security" }

[lints]
workspace = true
